package com.nari.sun.dao;

import com.nari.sun.Activity;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    int insertSelective(Activity record);
}