package com.nari.sun.dao;

import com.nari.sun.QzjMpRbphl;
import com.nari.sun.QzjMpRbphlExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface QzjMpRbphlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    @SelectProvider(type=QzjMpRbphlSqlProvider.class, method="countByExample")
    int countByExample(QzjMpRbphlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    @DeleteProvider(type=QzjMpRbphlSqlProvider.class, method="deleteByExample")
    int deleteByExample(QzjMpRbphlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    @Insert({
        "insert into qzj_mp_rbphl (ZDDZ, CLDLX, ",
        "CLDH, SJSJ, ZGDLBPHD, ",
        "ZGDLBPHDCXSJ, ZDDLBPHD, ",
        "ZDDLBPHDCXSJ, DYBPHDJCSJ, ",
        "DYBPHDHGL, DYBPHDCXL, ",
        "DYBPHDCSXSJ, ZGDYBPHD, ",
        "ZGDYBPHDCXSJ, ZDDYBPHD, ",
        "ZDDYBPHDCXSJ, XBZ, ",
        "XDYBPHD, XDLBPHD, ",
        "DYBPHDPJZ, DYBPHDPJZ_95, ",
        "DLBPHDPJZ, DLBPHDPJZ_95, ",
        "LAST_TIME, COPYTIME)",
        "values (#{zddz,jdbcType=VARCHAR}, #{cldlx,jdbcType=DECIMAL}, ",
        "#{cldh,jdbcType=VARCHAR}, #{sjsj,jdbcType=DATE}, #{zgdlbphd,jdbcType=DECIMAL}, ",
        "#{zgdlbphdcxsj,jdbcType=DATE}, #{zddlbphd,jdbcType=DECIMAL}, ",
        "#{zddlbphdcxsj,jdbcType=DATE}, #{dybphdjcsj,jdbcType=DECIMAL}, ",
        "#{dybphdhgl,jdbcType=DECIMAL}, #{dybphdcxl,jdbcType=DECIMAL}, ",
        "#{dybphdcsxsj,jdbcType=DECIMAL}, #{zgdybphd,jdbcType=DECIMAL}, ",
        "#{zgdybphdcxsj,jdbcType=DATE}, #{zddybphd,jdbcType=DECIMAL}, ",
        "#{zddybphdcxsj,jdbcType=DATE}, #{xbz,jdbcType=DECIMAL}, ",
        "#{xdybphd,jdbcType=DECIMAL}, #{xdlbphd,jdbcType=DECIMAL}, ",
        "#{dybphdpjz,jdbcType=DECIMAL}, #{dybphdpjz95,jdbcType=DECIMAL}, ",
        "#{dlbphdpjz,jdbcType=DECIMAL}, #{dlbphdpjz95,jdbcType=DECIMAL}, ",
        "#{lastTime,jdbcType=TIMESTAMP}, #{copytime,jdbcType=DATE})"
    })
    int insert(QzjMpRbphl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    @InsertProvider(type=QzjMpRbphlSqlProvider.class, method="insertSelective")
    int insertSelective(QzjMpRbphl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    @SelectProvider(type=QzjMpRbphlSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ZDDZ", property="zddz", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLDLX", property="cldlx", jdbcType=JdbcType.DECIMAL),
        @Result(column="CLDH", property="cldh", jdbcType=JdbcType.VARCHAR),
        @Result(column="SJSJ", property="sjsj", jdbcType=JdbcType.DATE),
        @Result(column="ZGDLBPHD", property="zgdlbphd", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZGDLBPHDCXSJ", property="zgdlbphdcxsj", jdbcType=JdbcType.DATE),
        @Result(column="ZDDLBPHD", property="zddlbphd", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZDDLBPHDCXSJ", property="zddlbphdcxsj", jdbcType=JdbcType.DATE),
        @Result(column="DYBPHDJCSJ", property="dybphdjcsj", jdbcType=JdbcType.DECIMAL),
        @Result(column="DYBPHDHGL", property="dybphdhgl", jdbcType=JdbcType.DECIMAL),
        @Result(column="DYBPHDCXL", property="dybphdcxl", jdbcType=JdbcType.DECIMAL),
        @Result(column="DYBPHDCSXSJ", property="dybphdcsxsj", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZGDYBPHD", property="zgdybphd", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZGDYBPHDCXSJ", property="zgdybphdcxsj", jdbcType=JdbcType.DATE),
        @Result(column="ZDDYBPHD", property="zddybphd", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZDDYBPHDCXSJ", property="zddybphdcxsj", jdbcType=JdbcType.DATE),
        @Result(column="XBZ", property="xbz", jdbcType=JdbcType.DECIMAL),
        @Result(column="XDYBPHD", property="xdybphd", jdbcType=JdbcType.DECIMAL),
        @Result(column="XDLBPHD", property="xdlbphd", jdbcType=JdbcType.DECIMAL),
        @Result(column="DYBPHDPJZ", property="dybphdpjz", jdbcType=JdbcType.DECIMAL),
        @Result(column="DYBPHDPJZ_95", property="dybphdpjz95", jdbcType=JdbcType.DECIMAL),
        @Result(column="DLBPHDPJZ", property="dlbphdpjz", jdbcType=JdbcType.DECIMAL),
        @Result(column="DLBPHDPJZ_95", property="dlbphdpjz95", jdbcType=JdbcType.DECIMAL),
        @Result(column="LAST_TIME", property="lastTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="COPYTIME", property="copytime", jdbcType=JdbcType.DATE)
    })
    List<QzjMpRbphl> selectByExample(QzjMpRbphlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    @UpdateProvider(type=QzjMpRbphlSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") QzjMpRbphl record, @Param("example") QzjMpRbphlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    @UpdateProvider(type=QzjMpRbphlSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") QzjMpRbphl record, @Param("example") QzjMpRbphlExample example);
}