package com.nari.sun;

import java.math.BigDecimal;
import java.util.Date;

public class QzjMpRbphl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZDDZ
     *
     * @mbggenerated
     */
    private String zddz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.CLDLX
     *
     * @mbggenerated
     */
    private Short cldlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.CLDH
     *
     * @mbggenerated
     */
    private String cldh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.SJSJ
     *
     * @mbggenerated
     */
    private Date sjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZGDLBPHD
     *
     * @mbggenerated
     */
    private BigDecimal zgdlbphd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZGDLBPHDCXSJ
     *
     * @mbggenerated
     */
    private Date zgdlbphdcxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZDDLBPHD
     *
     * @mbggenerated
     */
    private BigDecimal zddlbphd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZDDLBPHDCXSJ
     *
     * @mbggenerated
     */
    private Date zddlbphdcxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.DYBPHDJCSJ
     *
     * @mbggenerated
     */
    private Integer dybphdjcsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.DYBPHDHGL
     *
     * @mbggenerated
     */
    private BigDecimal dybphdhgl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.DYBPHDCXL
     *
     * @mbggenerated
     */
    private BigDecimal dybphdcxl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.DYBPHDCSXSJ
     *
     * @mbggenerated
     */
    private Integer dybphdcsxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZGDYBPHD
     *
     * @mbggenerated
     */
    private BigDecimal zgdybphd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZGDYBPHDCXSJ
     *
     * @mbggenerated
     */
    private Date zgdybphdcxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZDDYBPHD
     *
     * @mbggenerated
     */
    private BigDecimal zddybphd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.ZDDYBPHDCXSJ
     *
     * @mbggenerated
     */
    private Date zddybphdcxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.XBZ
     *
     * @mbggenerated
     */
    private Short xbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.XDYBPHD
     *
     * @mbggenerated
     */
    private BigDecimal xdybphd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.XDLBPHD
     *
     * @mbggenerated
     */
    private BigDecimal xdlbphd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.DYBPHDPJZ
     *
     * @mbggenerated
     */
    private BigDecimal dybphdpjz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.DYBPHDPJZ_95
     *
     * @mbggenerated
     */
    private BigDecimal dybphdpjz95;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.DLBPHDPJZ
     *
     * @mbggenerated
     */
    private BigDecimal dlbphdpjz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.DLBPHDPJZ_95
     *
     * @mbggenerated
     */
    private BigDecimal dlbphdpjz95;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.LAST_TIME
     *
     * @mbggenerated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qzj_mp_rbphl.COPYTIME
     *
     * @mbggenerated
     */
    private Date copytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZDDZ
     *
     * @return the value of qzj_mp_rbphl.ZDDZ
     *
     * @mbggenerated
     */
    public String getZddz() {
        return zddz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZDDZ
     *
     * @param zddz the value for qzj_mp_rbphl.ZDDZ
     *
     * @mbggenerated
     */
    public void setZddz(String zddz) {
        this.zddz = zddz == null ? null : zddz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.CLDLX
     *
     * @return the value of qzj_mp_rbphl.CLDLX
     *
     * @mbggenerated
     */
    public Short getCldlx() {
        return cldlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.CLDLX
     *
     * @param cldlx the value for qzj_mp_rbphl.CLDLX
     *
     * @mbggenerated
     */
    public void setCldlx(Short cldlx) {
        this.cldlx = cldlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.CLDH
     *
     * @return the value of qzj_mp_rbphl.CLDH
     *
     * @mbggenerated
     */
    public String getCldh() {
        return cldh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.CLDH
     *
     * @param cldh the value for qzj_mp_rbphl.CLDH
     *
     * @mbggenerated
     */
    public void setCldh(String cldh) {
        this.cldh = cldh == null ? null : cldh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.SJSJ
     *
     * @return the value of qzj_mp_rbphl.SJSJ
     *
     * @mbggenerated
     */
    public Date getSjsj() {
        return sjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.SJSJ
     *
     * @param sjsj the value for qzj_mp_rbphl.SJSJ
     *
     * @mbggenerated
     */
    public void setSjsj(Date sjsj) {
        this.sjsj = sjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZGDLBPHD
     *
     * @return the value of qzj_mp_rbphl.ZGDLBPHD
     *
     * @mbggenerated
     */
    public BigDecimal getZgdlbphd() {
        return zgdlbphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZGDLBPHD
     *
     * @param zgdlbphd the value for qzj_mp_rbphl.ZGDLBPHD
     *
     * @mbggenerated
     */
    public void setZgdlbphd(BigDecimal zgdlbphd) {
        this.zgdlbphd = zgdlbphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZGDLBPHDCXSJ
     *
     * @return the value of qzj_mp_rbphl.ZGDLBPHDCXSJ
     *
     * @mbggenerated
     */
    public Date getZgdlbphdcxsj() {
        return zgdlbphdcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZGDLBPHDCXSJ
     *
     * @param zgdlbphdcxsj the value for qzj_mp_rbphl.ZGDLBPHDCXSJ
     *
     * @mbggenerated
     */
    public void setZgdlbphdcxsj(Date zgdlbphdcxsj) {
        this.zgdlbphdcxsj = zgdlbphdcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZDDLBPHD
     *
     * @return the value of qzj_mp_rbphl.ZDDLBPHD
     *
     * @mbggenerated
     */
    public BigDecimal getZddlbphd() {
        return zddlbphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZDDLBPHD
     *
     * @param zddlbphd the value for qzj_mp_rbphl.ZDDLBPHD
     *
     * @mbggenerated
     */
    public void setZddlbphd(BigDecimal zddlbphd) {
        this.zddlbphd = zddlbphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZDDLBPHDCXSJ
     *
     * @return the value of qzj_mp_rbphl.ZDDLBPHDCXSJ
     *
     * @mbggenerated
     */
    public Date getZddlbphdcxsj() {
        return zddlbphdcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZDDLBPHDCXSJ
     *
     * @param zddlbphdcxsj the value for qzj_mp_rbphl.ZDDLBPHDCXSJ
     *
     * @mbggenerated
     */
    public void setZddlbphdcxsj(Date zddlbphdcxsj) {
        this.zddlbphdcxsj = zddlbphdcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.DYBPHDJCSJ
     *
     * @return the value of qzj_mp_rbphl.DYBPHDJCSJ
     *
     * @mbggenerated
     */
    public Integer getDybphdjcsj() {
        return dybphdjcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.DYBPHDJCSJ
     *
     * @param dybphdjcsj the value for qzj_mp_rbphl.DYBPHDJCSJ
     *
     * @mbggenerated
     */
    public void setDybphdjcsj(Integer dybphdjcsj) {
        this.dybphdjcsj = dybphdjcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.DYBPHDHGL
     *
     * @return the value of qzj_mp_rbphl.DYBPHDHGL
     *
     * @mbggenerated
     */
    public BigDecimal getDybphdhgl() {
        return dybphdhgl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.DYBPHDHGL
     *
     * @param dybphdhgl the value for qzj_mp_rbphl.DYBPHDHGL
     *
     * @mbggenerated
     */
    public void setDybphdhgl(BigDecimal dybphdhgl) {
        this.dybphdhgl = dybphdhgl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.DYBPHDCXL
     *
     * @return the value of qzj_mp_rbphl.DYBPHDCXL
     *
     * @mbggenerated
     */
    public BigDecimal getDybphdcxl() {
        return dybphdcxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.DYBPHDCXL
     *
     * @param dybphdcxl the value for qzj_mp_rbphl.DYBPHDCXL
     *
     * @mbggenerated
     */
    public void setDybphdcxl(BigDecimal dybphdcxl) {
        this.dybphdcxl = dybphdcxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.DYBPHDCSXSJ
     *
     * @return the value of qzj_mp_rbphl.DYBPHDCSXSJ
     *
     * @mbggenerated
     */
    public Integer getDybphdcsxsj() {
        return dybphdcsxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.DYBPHDCSXSJ
     *
     * @param dybphdcsxsj the value for qzj_mp_rbphl.DYBPHDCSXSJ
     *
     * @mbggenerated
     */
    public void setDybphdcsxsj(Integer dybphdcsxsj) {
        this.dybphdcsxsj = dybphdcsxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZGDYBPHD
     *
     * @return the value of qzj_mp_rbphl.ZGDYBPHD
     *
     * @mbggenerated
     */
    public BigDecimal getZgdybphd() {
        return zgdybphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZGDYBPHD
     *
     * @param zgdybphd the value for qzj_mp_rbphl.ZGDYBPHD
     *
     * @mbggenerated
     */
    public void setZgdybphd(BigDecimal zgdybphd) {
        this.zgdybphd = zgdybphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZGDYBPHDCXSJ
     *
     * @return the value of qzj_mp_rbphl.ZGDYBPHDCXSJ
     *
     * @mbggenerated
     */
    public Date getZgdybphdcxsj() {
        return zgdybphdcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZGDYBPHDCXSJ
     *
     * @param zgdybphdcxsj the value for qzj_mp_rbphl.ZGDYBPHDCXSJ
     *
     * @mbggenerated
     */
    public void setZgdybphdcxsj(Date zgdybphdcxsj) {
        this.zgdybphdcxsj = zgdybphdcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZDDYBPHD
     *
     * @return the value of qzj_mp_rbphl.ZDDYBPHD
     *
     * @mbggenerated
     */
    public BigDecimal getZddybphd() {
        return zddybphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZDDYBPHD
     *
     * @param zddybphd the value for qzj_mp_rbphl.ZDDYBPHD
     *
     * @mbggenerated
     */
    public void setZddybphd(BigDecimal zddybphd) {
        this.zddybphd = zddybphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.ZDDYBPHDCXSJ
     *
     * @return the value of qzj_mp_rbphl.ZDDYBPHDCXSJ
     *
     * @mbggenerated
     */
    public Date getZddybphdcxsj() {
        return zddybphdcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.ZDDYBPHDCXSJ
     *
     * @param zddybphdcxsj the value for qzj_mp_rbphl.ZDDYBPHDCXSJ
     *
     * @mbggenerated
     */
    public void setZddybphdcxsj(Date zddybphdcxsj) {
        this.zddybphdcxsj = zddybphdcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.XBZ
     *
     * @return the value of qzj_mp_rbphl.XBZ
     *
     * @mbggenerated
     */
    public Short getXbz() {
        return xbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.XBZ
     *
     * @param xbz the value for qzj_mp_rbphl.XBZ
     *
     * @mbggenerated
     */
    public void setXbz(Short xbz) {
        this.xbz = xbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.XDYBPHD
     *
     * @return the value of qzj_mp_rbphl.XDYBPHD
     *
     * @mbggenerated
     */
    public BigDecimal getXdybphd() {
        return xdybphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.XDYBPHD
     *
     * @param xdybphd the value for qzj_mp_rbphl.XDYBPHD
     *
     * @mbggenerated
     */
    public void setXdybphd(BigDecimal xdybphd) {
        this.xdybphd = xdybphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.XDLBPHD
     *
     * @return the value of qzj_mp_rbphl.XDLBPHD
     *
     * @mbggenerated
     */
    public BigDecimal getXdlbphd() {
        return xdlbphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.XDLBPHD
     *
     * @param xdlbphd the value for qzj_mp_rbphl.XDLBPHD
     *
     * @mbggenerated
     */
    public void setXdlbphd(BigDecimal xdlbphd) {
        this.xdlbphd = xdlbphd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.DYBPHDPJZ
     *
     * @return the value of qzj_mp_rbphl.DYBPHDPJZ
     *
     * @mbggenerated
     */
    public BigDecimal getDybphdpjz() {
        return dybphdpjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.DYBPHDPJZ
     *
     * @param dybphdpjz the value for qzj_mp_rbphl.DYBPHDPJZ
     *
     * @mbggenerated
     */
    public void setDybphdpjz(BigDecimal dybphdpjz) {
        this.dybphdpjz = dybphdpjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.DYBPHDPJZ_95
     *
     * @return the value of qzj_mp_rbphl.DYBPHDPJZ_95
     *
     * @mbggenerated
     */
    public BigDecimal getDybphdpjz95() {
        return dybphdpjz95;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.DYBPHDPJZ_95
     *
     * @param dybphdpjz95 the value for qzj_mp_rbphl.DYBPHDPJZ_95
     *
     * @mbggenerated
     */
    public void setDybphdpjz95(BigDecimal dybphdpjz95) {
        this.dybphdpjz95 = dybphdpjz95;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.DLBPHDPJZ
     *
     * @return the value of qzj_mp_rbphl.DLBPHDPJZ
     *
     * @mbggenerated
     */
    public BigDecimal getDlbphdpjz() {
        return dlbphdpjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.DLBPHDPJZ
     *
     * @param dlbphdpjz the value for qzj_mp_rbphl.DLBPHDPJZ
     *
     * @mbggenerated
     */
    public void setDlbphdpjz(BigDecimal dlbphdpjz) {
        this.dlbphdpjz = dlbphdpjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.DLBPHDPJZ_95
     *
     * @return the value of qzj_mp_rbphl.DLBPHDPJZ_95
     *
     * @mbggenerated
     */
    public BigDecimal getDlbphdpjz95() {
        return dlbphdpjz95;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.DLBPHDPJZ_95
     *
     * @param dlbphdpjz95 the value for qzj_mp_rbphl.DLBPHDPJZ_95
     *
     * @mbggenerated
     */
    public void setDlbphdpjz95(BigDecimal dlbphdpjz95) {
        this.dlbphdpjz95 = dlbphdpjz95;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.LAST_TIME
     *
     * @return the value of qzj_mp_rbphl.LAST_TIME
     *
     * @mbggenerated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.LAST_TIME
     *
     * @param lastTime the value for qzj_mp_rbphl.LAST_TIME
     *
     * @mbggenerated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qzj_mp_rbphl.COPYTIME
     *
     * @return the value of qzj_mp_rbphl.COPYTIME
     *
     * @mbggenerated
     */
    public Date getCopytime() {
        return copytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qzj_mp_rbphl.COPYTIME
     *
     * @param copytime the value for qzj_mp_rbphl.COPYTIME
     *
     * @mbggenerated
     */
    public void setCopytime(Date copytime) {
        this.copytime = copytime;
    }
}