package com.nari.sun;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class QzjMpRbphlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public QzjMpRbphlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andZddzIsNull() {
            addCriterion("ZDDZ is null");
            return (Criteria) this;
        }

        public Criteria andZddzIsNotNull() {
            addCriterion("ZDDZ is not null");
            return (Criteria) this;
        }

        public Criteria andZddzEqualTo(String value) {
            addCriterion("ZDDZ =", value, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzNotEqualTo(String value) {
            addCriterion("ZDDZ <>", value, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzGreaterThan(String value) {
            addCriterion("ZDDZ >", value, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzGreaterThanOrEqualTo(String value) {
            addCriterion("ZDDZ >=", value, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzLessThan(String value) {
            addCriterion("ZDDZ <", value, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzLessThanOrEqualTo(String value) {
            addCriterion("ZDDZ <=", value, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzLike(String value) {
            addCriterion("ZDDZ like", value, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzNotLike(String value) {
            addCriterion("ZDDZ not like", value, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzIn(List<String> values) {
            addCriterion("ZDDZ in", values, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzNotIn(List<String> values) {
            addCriterion("ZDDZ not in", values, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzBetween(String value1, String value2) {
            addCriterion("ZDDZ between", value1, value2, "zddz");
            return (Criteria) this;
        }

        public Criteria andZddzNotBetween(String value1, String value2) {
            addCriterion("ZDDZ not between", value1, value2, "zddz");
            return (Criteria) this;
        }

        public Criteria andCldlxIsNull() {
            addCriterion("CLDLX is null");
            return (Criteria) this;
        }

        public Criteria andCldlxIsNotNull() {
            addCriterion("CLDLX is not null");
            return (Criteria) this;
        }

        public Criteria andCldlxEqualTo(Short value) {
            addCriterion("CLDLX =", value, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxNotEqualTo(Short value) {
            addCriterion("CLDLX <>", value, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxGreaterThan(Short value) {
            addCriterion("CLDLX >", value, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxGreaterThanOrEqualTo(Short value) {
            addCriterion("CLDLX >=", value, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxLessThan(Short value) {
            addCriterion("CLDLX <", value, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxLessThanOrEqualTo(Short value) {
            addCriterion("CLDLX <=", value, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxIn(List<Short> values) {
            addCriterion("CLDLX in", values, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxNotIn(List<Short> values) {
            addCriterion("CLDLX not in", values, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxBetween(Short value1, Short value2) {
            addCriterion("CLDLX between", value1, value2, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldlxNotBetween(Short value1, Short value2) {
            addCriterion("CLDLX not between", value1, value2, "cldlx");
            return (Criteria) this;
        }

        public Criteria andCldhIsNull() {
            addCriterion("CLDH is null");
            return (Criteria) this;
        }

        public Criteria andCldhIsNotNull() {
            addCriterion("CLDH is not null");
            return (Criteria) this;
        }

        public Criteria andCldhEqualTo(String value) {
            addCriterion("CLDH =", value, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhNotEqualTo(String value) {
            addCriterion("CLDH <>", value, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhGreaterThan(String value) {
            addCriterion("CLDH >", value, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhGreaterThanOrEqualTo(String value) {
            addCriterion("CLDH >=", value, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhLessThan(String value) {
            addCriterion("CLDH <", value, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhLessThanOrEqualTo(String value) {
            addCriterion("CLDH <=", value, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhLike(String value) {
            addCriterion("CLDH like", value, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhNotLike(String value) {
            addCriterion("CLDH not like", value, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhIn(List<String> values) {
            addCriterion("CLDH in", values, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhNotIn(List<String> values) {
            addCriterion("CLDH not in", values, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhBetween(String value1, String value2) {
            addCriterion("CLDH between", value1, value2, "cldh");
            return (Criteria) this;
        }

        public Criteria andCldhNotBetween(String value1, String value2) {
            addCriterion("CLDH not between", value1, value2, "cldh");
            return (Criteria) this;
        }

        public Criteria andSjsjIsNull() {
            addCriterion("SJSJ is null");
            return (Criteria) this;
        }

        public Criteria andSjsjIsNotNull() {
            addCriterion("SJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andSjsjEqualTo(Date value) {
            addCriterionForJDBCDate("SJSJ =", value, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("SJSJ <>", value, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjGreaterThan(Date value) {
            addCriterionForJDBCDate("SJSJ >", value, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SJSJ >=", value, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjLessThan(Date value) {
            addCriterionForJDBCDate("SJSJ <", value, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SJSJ <=", value, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjIn(List<Date> values) {
            addCriterionForJDBCDate("SJSJ in", values, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("SJSJ not in", values, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SJSJ between", value1, value2, "sjsj");
            return (Criteria) this;
        }

        public Criteria andSjsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SJSJ not between", value1, value2, "sjsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdIsNull() {
            addCriterion("ZGDLBPHD is null");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdIsNotNull() {
            addCriterion("ZGDLBPHD is not null");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdEqualTo(BigDecimal value) {
            addCriterion("ZGDLBPHD =", value, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdNotEqualTo(BigDecimal value) {
            addCriterion("ZGDLBPHD <>", value, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdGreaterThan(BigDecimal value) {
            addCriterion("ZGDLBPHD >", value, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ZGDLBPHD >=", value, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdLessThan(BigDecimal value) {
            addCriterion("ZGDLBPHD <", value, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ZGDLBPHD <=", value, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdIn(List<BigDecimal> values) {
            addCriterion("ZGDLBPHD in", values, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdNotIn(List<BigDecimal> values) {
            addCriterion("ZGDLBPHD not in", values, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZGDLBPHD between", value1, value2, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZGDLBPHD not between", value1, value2, "zgdlbphd");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjIsNull() {
            addCriterion("ZGDLBPHDCXSJ is null");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjIsNotNull() {
            addCriterion("ZGDLBPHDCXSJ is not null");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjEqualTo(Date value) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ =", value, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ <>", value, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjGreaterThan(Date value) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ >", value, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ >=", value, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjLessThan(Date value) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ <", value, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ <=", value, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjIn(List<Date> values) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ in", values, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ not in", values, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ between", value1, value2, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdlbphdcxsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZGDLBPHDCXSJ not between", value1, value2, "zgdlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdIsNull() {
            addCriterion("ZDDLBPHD is null");
            return (Criteria) this;
        }

        public Criteria andZddlbphdIsNotNull() {
            addCriterion("ZDDLBPHD is not null");
            return (Criteria) this;
        }

        public Criteria andZddlbphdEqualTo(BigDecimal value) {
            addCriterion("ZDDLBPHD =", value, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdNotEqualTo(BigDecimal value) {
            addCriterion("ZDDLBPHD <>", value, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdGreaterThan(BigDecimal value) {
            addCriterion("ZDDLBPHD >", value, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ZDDLBPHD >=", value, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdLessThan(BigDecimal value) {
            addCriterion("ZDDLBPHD <", value, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ZDDLBPHD <=", value, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdIn(List<BigDecimal> values) {
            addCriterion("ZDDLBPHD in", values, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdNotIn(List<BigDecimal> values) {
            addCriterion("ZDDLBPHD not in", values, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZDDLBPHD between", value1, value2, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZDDLBPHD not between", value1, value2, "zddlbphd");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjIsNull() {
            addCriterion("ZDDLBPHDCXSJ is null");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjIsNotNull() {
            addCriterion("ZDDLBPHDCXSJ is not null");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjEqualTo(Date value) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ =", value, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ <>", value, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjGreaterThan(Date value) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ >", value, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ >=", value, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjLessThan(Date value) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ <", value, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ <=", value, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjIn(List<Date> values) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ in", values, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ not in", values, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ between", value1, value2, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddlbphdcxsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZDDLBPHDCXSJ not between", value1, value2, "zddlbphdcxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjIsNull() {
            addCriterion("DYBPHDJCSJ is null");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjIsNotNull() {
            addCriterion("DYBPHDJCSJ is not null");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjEqualTo(Integer value) {
            addCriterion("DYBPHDJCSJ =", value, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjNotEqualTo(Integer value) {
            addCriterion("DYBPHDJCSJ <>", value, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjGreaterThan(Integer value) {
            addCriterion("DYBPHDJCSJ >", value, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjGreaterThanOrEqualTo(Integer value) {
            addCriterion("DYBPHDJCSJ >=", value, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjLessThan(Integer value) {
            addCriterion("DYBPHDJCSJ <", value, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjLessThanOrEqualTo(Integer value) {
            addCriterion("DYBPHDJCSJ <=", value, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjIn(List<Integer> values) {
            addCriterion("DYBPHDJCSJ in", values, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjNotIn(List<Integer> values) {
            addCriterion("DYBPHDJCSJ not in", values, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjBetween(Integer value1, Integer value2) {
            addCriterion("DYBPHDJCSJ between", value1, value2, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdjcsjNotBetween(Integer value1, Integer value2) {
            addCriterion("DYBPHDJCSJ not between", value1, value2, "dybphdjcsj");
            return (Criteria) this;
        }

        public Criteria andDybphdhglIsNull() {
            addCriterion("DYBPHDHGL is null");
            return (Criteria) this;
        }

        public Criteria andDybphdhglIsNotNull() {
            addCriterion("DYBPHDHGL is not null");
            return (Criteria) this;
        }

        public Criteria andDybphdhglEqualTo(BigDecimal value) {
            addCriterion("DYBPHDHGL =", value, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglNotEqualTo(BigDecimal value) {
            addCriterion("DYBPHDHGL <>", value, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglGreaterThan(BigDecimal value) {
            addCriterion("DYBPHDHGL >", value, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DYBPHDHGL >=", value, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglLessThan(BigDecimal value) {
            addCriterion("DYBPHDHGL <", value, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DYBPHDHGL <=", value, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglIn(List<BigDecimal> values) {
            addCriterion("DYBPHDHGL in", values, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglNotIn(List<BigDecimal> values) {
            addCriterion("DYBPHDHGL not in", values, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DYBPHDHGL between", value1, value2, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdhglNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DYBPHDHGL not between", value1, value2, "dybphdhgl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlIsNull() {
            addCriterion("DYBPHDCXL is null");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlIsNotNull() {
            addCriterion("DYBPHDCXL is not null");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlEqualTo(BigDecimal value) {
            addCriterion("DYBPHDCXL =", value, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlNotEqualTo(BigDecimal value) {
            addCriterion("DYBPHDCXL <>", value, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlGreaterThan(BigDecimal value) {
            addCriterion("DYBPHDCXL >", value, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DYBPHDCXL >=", value, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlLessThan(BigDecimal value) {
            addCriterion("DYBPHDCXL <", value, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DYBPHDCXL <=", value, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlIn(List<BigDecimal> values) {
            addCriterion("DYBPHDCXL in", values, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlNotIn(List<BigDecimal> values) {
            addCriterion("DYBPHDCXL not in", values, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DYBPHDCXL between", value1, value2, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcxlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DYBPHDCXL not between", value1, value2, "dybphdcxl");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjIsNull() {
            addCriterion("DYBPHDCSXSJ is null");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjIsNotNull() {
            addCriterion("DYBPHDCSXSJ is not null");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjEqualTo(Integer value) {
            addCriterion("DYBPHDCSXSJ =", value, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjNotEqualTo(Integer value) {
            addCriterion("DYBPHDCSXSJ <>", value, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjGreaterThan(Integer value) {
            addCriterion("DYBPHDCSXSJ >", value, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjGreaterThanOrEqualTo(Integer value) {
            addCriterion("DYBPHDCSXSJ >=", value, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjLessThan(Integer value) {
            addCriterion("DYBPHDCSXSJ <", value, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjLessThanOrEqualTo(Integer value) {
            addCriterion("DYBPHDCSXSJ <=", value, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjIn(List<Integer> values) {
            addCriterion("DYBPHDCSXSJ in", values, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjNotIn(List<Integer> values) {
            addCriterion("DYBPHDCSXSJ not in", values, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjBetween(Integer value1, Integer value2) {
            addCriterion("DYBPHDCSXSJ between", value1, value2, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andDybphdcsxsjNotBetween(Integer value1, Integer value2) {
            addCriterion("DYBPHDCSXSJ not between", value1, value2, "dybphdcsxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdIsNull() {
            addCriterion("ZGDYBPHD is null");
            return (Criteria) this;
        }

        public Criteria andZgdybphdIsNotNull() {
            addCriterion("ZGDYBPHD is not null");
            return (Criteria) this;
        }

        public Criteria andZgdybphdEqualTo(BigDecimal value) {
            addCriterion("ZGDYBPHD =", value, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdNotEqualTo(BigDecimal value) {
            addCriterion("ZGDYBPHD <>", value, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdGreaterThan(BigDecimal value) {
            addCriterion("ZGDYBPHD >", value, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ZGDYBPHD >=", value, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdLessThan(BigDecimal value) {
            addCriterion("ZGDYBPHD <", value, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ZGDYBPHD <=", value, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdIn(List<BigDecimal> values) {
            addCriterion("ZGDYBPHD in", values, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdNotIn(List<BigDecimal> values) {
            addCriterion("ZGDYBPHD not in", values, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZGDYBPHD between", value1, value2, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZGDYBPHD not between", value1, value2, "zgdybphd");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjIsNull() {
            addCriterion("ZGDYBPHDCXSJ is null");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjIsNotNull() {
            addCriterion("ZGDYBPHDCXSJ is not null");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjEqualTo(Date value) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ =", value, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ <>", value, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjGreaterThan(Date value) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ >", value, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ >=", value, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjLessThan(Date value) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ <", value, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ <=", value, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjIn(List<Date> values) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ in", values, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ not in", values, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ between", value1, value2, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZgdybphdcxsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZGDYBPHDCXSJ not between", value1, value2, "zgdybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdIsNull() {
            addCriterion("ZDDYBPHD is null");
            return (Criteria) this;
        }

        public Criteria andZddybphdIsNotNull() {
            addCriterion("ZDDYBPHD is not null");
            return (Criteria) this;
        }

        public Criteria andZddybphdEqualTo(BigDecimal value) {
            addCriterion("ZDDYBPHD =", value, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdNotEqualTo(BigDecimal value) {
            addCriterion("ZDDYBPHD <>", value, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdGreaterThan(BigDecimal value) {
            addCriterion("ZDDYBPHD >", value, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ZDDYBPHD >=", value, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdLessThan(BigDecimal value) {
            addCriterion("ZDDYBPHD <", value, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ZDDYBPHD <=", value, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdIn(List<BigDecimal> values) {
            addCriterion("ZDDYBPHD in", values, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdNotIn(List<BigDecimal> values) {
            addCriterion("ZDDYBPHD not in", values, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZDDYBPHD between", value1, value2, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZDDYBPHD not between", value1, value2, "zddybphd");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjIsNull() {
            addCriterion("ZDDYBPHDCXSJ is null");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjIsNotNull() {
            addCriterion("ZDDYBPHDCXSJ is not null");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjEqualTo(Date value) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ =", value, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ <>", value, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjGreaterThan(Date value) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ >", value, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ >=", value, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjLessThan(Date value) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ <", value, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ <=", value, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjIn(List<Date> values) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ in", values, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ not in", values, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ between", value1, value2, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andZddybphdcxsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZDDYBPHDCXSJ not between", value1, value2, "zddybphdcxsj");
            return (Criteria) this;
        }

        public Criteria andXbzIsNull() {
            addCriterion("XBZ is null");
            return (Criteria) this;
        }

        public Criteria andXbzIsNotNull() {
            addCriterion("XBZ is not null");
            return (Criteria) this;
        }

        public Criteria andXbzEqualTo(Short value) {
            addCriterion("XBZ =", value, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzNotEqualTo(Short value) {
            addCriterion("XBZ <>", value, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzGreaterThan(Short value) {
            addCriterion("XBZ >", value, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzGreaterThanOrEqualTo(Short value) {
            addCriterion("XBZ >=", value, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzLessThan(Short value) {
            addCriterion("XBZ <", value, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzLessThanOrEqualTo(Short value) {
            addCriterion("XBZ <=", value, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzIn(List<Short> values) {
            addCriterion("XBZ in", values, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzNotIn(List<Short> values) {
            addCriterion("XBZ not in", values, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzBetween(Short value1, Short value2) {
            addCriterion("XBZ between", value1, value2, "xbz");
            return (Criteria) this;
        }

        public Criteria andXbzNotBetween(Short value1, Short value2) {
            addCriterion("XBZ not between", value1, value2, "xbz");
            return (Criteria) this;
        }

        public Criteria andXdybphdIsNull() {
            addCriterion("XDYBPHD is null");
            return (Criteria) this;
        }

        public Criteria andXdybphdIsNotNull() {
            addCriterion("XDYBPHD is not null");
            return (Criteria) this;
        }

        public Criteria andXdybphdEqualTo(BigDecimal value) {
            addCriterion("XDYBPHD =", value, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdNotEqualTo(BigDecimal value) {
            addCriterion("XDYBPHD <>", value, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdGreaterThan(BigDecimal value) {
            addCriterion("XDYBPHD >", value, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("XDYBPHD >=", value, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdLessThan(BigDecimal value) {
            addCriterion("XDYBPHD <", value, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("XDYBPHD <=", value, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdIn(List<BigDecimal> values) {
            addCriterion("XDYBPHD in", values, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdNotIn(List<BigDecimal> values) {
            addCriterion("XDYBPHD not in", values, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XDYBPHD between", value1, value2, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdybphdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XDYBPHD not between", value1, value2, "xdybphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdIsNull() {
            addCriterion("XDLBPHD is null");
            return (Criteria) this;
        }

        public Criteria andXdlbphdIsNotNull() {
            addCriterion("XDLBPHD is not null");
            return (Criteria) this;
        }

        public Criteria andXdlbphdEqualTo(BigDecimal value) {
            addCriterion("XDLBPHD =", value, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdNotEqualTo(BigDecimal value) {
            addCriterion("XDLBPHD <>", value, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdGreaterThan(BigDecimal value) {
            addCriterion("XDLBPHD >", value, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("XDLBPHD >=", value, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdLessThan(BigDecimal value) {
            addCriterion("XDLBPHD <", value, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("XDLBPHD <=", value, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdIn(List<BigDecimal> values) {
            addCriterion("XDLBPHD in", values, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdNotIn(List<BigDecimal> values) {
            addCriterion("XDLBPHD not in", values, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XDLBPHD between", value1, value2, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andXdlbphdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XDLBPHD not between", value1, value2, "xdlbphd");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzIsNull() {
            addCriterion("DYBPHDPJZ is null");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzIsNotNull() {
            addCriterion("DYBPHDPJZ is not null");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzEqualTo(BigDecimal value) {
            addCriterion("DYBPHDPJZ =", value, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzNotEqualTo(BigDecimal value) {
            addCriterion("DYBPHDPJZ <>", value, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzGreaterThan(BigDecimal value) {
            addCriterion("DYBPHDPJZ >", value, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DYBPHDPJZ >=", value, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzLessThan(BigDecimal value) {
            addCriterion("DYBPHDPJZ <", value, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DYBPHDPJZ <=", value, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzIn(List<BigDecimal> values) {
            addCriterion("DYBPHDPJZ in", values, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzNotIn(List<BigDecimal> values) {
            addCriterion("DYBPHDPJZ not in", values, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DYBPHDPJZ between", value1, value2, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjzNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DYBPHDPJZ not between", value1, value2, "dybphdpjz");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95IsNull() {
            addCriterion("DYBPHDPJZ_95 is null");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95IsNotNull() {
            addCriterion("DYBPHDPJZ_95 is not null");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95EqualTo(BigDecimal value) {
            addCriterion("DYBPHDPJZ_95 =", value, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95NotEqualTo(BigDecimal value) {
            addCriterion("DYBPHDPJZ_95 <>", value, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95GreaterThan(BigDecimal value) {
            addCriterion("DYBPHDPJZ_95 >", value, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DYBPHDPJZ_95 >=", value, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95LessThan(BigDecimal value) {
            addCriterion("DYBPHDPJZ_95 <", value, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95LessThanOrEqualTo(BigDecimal value) {
            addCriterion("DYBPHDPJZ_95 <=", value, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95In(List<BigDecimal> values) {
            addCriterion("DYBPHDPJZ_95 in", values, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95NotIn(List<BigDecimal> values) {
            addCriterion("DYBPHDPJZ_95 not in", values, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("DYBPHDPJZ_95 between", value1, value2, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDybphdpjz95NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DYBPHDPJZ_95 not between", value1, value2, "dybphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzIsNull() {
            addCriterion("DLBPHDPJZ is null");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzIsNotNull() {
            addCriterion("DLBPHDPJZ is not null");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzEqualTo(BigDecimal value) {
            addCriterion("DLBPHDPJZ =", value, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzNotEqualTo(BigDecimal value) {
            addCriterion("DLBPHDPJZ <>", value, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzGreaterThan(BigDecimal value) {
            addCriterion("DLBPHDPJZ >", value, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DLBPHDPJZ >=", value, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzLessThan(BigDecimal value) {
            addCriterion("DLBPHDPJZ <", value, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DLBPHDPJZ <=", value, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzIn(List<BigDecimal> values) {
            addCriterion("DLBPHDPJZ in", values, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzNotIn(List<BigDecimal> values) {
            addCriterion("DLBPHDPJZ not in", values, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DLBPHDPJZ between", value1, value2, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjzNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DLBPHDPJZ not between", value1, value2, "dlbphdpjz");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95IsNull() {
            addCriterion("DLBPHDPJZ_95 is null");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95IsNotNull() {
            addCriterion("DLBPHDPJZ_95 is not null");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95EqualTo(BigDecimal value) {
            addCriterion("DLBPHDPJZ_95 =", value, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95NotEqualTo(BigDecimal value) {
            addCriterion("DLBPHDPJZ_95 <>", value, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95GreaterThan(BigDecimal value) {
            addCriterion("DLBPHDPJZ_95 >", value, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DLBPHDPJZ_95 >=", value, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95LessThan(BigDecimal value) {
            addCriterion("DLBPHDPJZ_95 <", value, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95LessThanOrEqualTo(BigDecimal value) {
            addCriterion("DLBPHDPJZ_95 <=", value, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95In(List<BigDecimal> values) {
            addCriterion("DLBPHDPJZ_95 in", values, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95NotIn(List<BigDecimal> values) {
            addCriterion("DLBPHDPJZ_95 not in", values, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("DLBPHDPJZ_95 between", value1, value2, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andDlbphdpjz95NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DLBPHDPJZ_95 not between", value1, value2, "dlbphdpjz95");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNull() {
            addCriterion("LAST_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNotNull() {
            addCriterion("LAST_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastTimeEqualTo(Date value) {
            addCriterion("LAST_TIME =", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotEqualTo(Date value) {
            addCriterion("LAST_TIME <>", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThan(Date value) {
            addCriterion("LAST_TIME >", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_TIME >=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThan(Date value) {
            addCriterion("LAST_TIME <", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_TIME <=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeIn(List<Date> values) {
            addCriterion("LAST_TIME in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotIn(List<Date> values) {
            addCriterion("LAST_TIME not in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_TIME between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_TIME not between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andCopytimeIsNull() {
            addCriterion("COPYTIME is null");
            return (Criteria) this;
        }

        public Criteria andCopytimeIsNotNull() {
            addCriterion("COPYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCopytimeEqualTo(Date value) {
            addCriterionForJDBCDate("COPYTIME =", value, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("COPYTIME <>", value, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeGreaterThan(Date value) {
            addCriterionForJDBCDate("COPYTIME >", value, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("COPYTIME >=", value, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeLessThan(Date value) {
            addCriterionForJDBCDate("COPYTIME <", value, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("COPYTIME <=", value, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeIn(List<Date> values) {
            addCriterionForJDBCDate("COPYTIME in", values, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("COPYTIME not in", values, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("COPYTIME between", value1, value2, "copytime");
            return (Criteria) this;
        }

        public Criteria andCopytimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("COPYTIME not between", value1, value2, "copytime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qzj_mp_rbphl
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}